### ISSUE TITLE
Like/Dislike doesn’t work when listening to a radio

### ISSUE THREAD

**Issue by nbd9** [nbd9/vscode-gmusic#1]
**Steps to reproduce:**
Launch GPMDP and start a radio station (ex: Feel Good Dance/EDM)
Launch VS Code and like the song.

**Expected results:**
The song is liked

**Additional information**
Seems to work when playing from a playlist, just not with a single song/radio station.

**Comment by benrosenblum** [comment]
Doesn't seem to be working for me with playlists either. I can play/pause and skip, but the rating commands seem to do nothing.

**Comment by nbd9** [comment]
After a long delay, this should be fixed in 5141ac90c08443d4adac0c0dfe2385f254ea947d
